### ISSUE TITLE
messed up grid?

### ISSUE THREAD

**Issue by soulgriever** [VazkiiModsArchive/GenCreator#1]
When holding the button to activate the grid by selecting it creates a grid that is sideways (x rather then square to select the block) no chat is communicated to say I have selected a block, I try to select the 2nd block but nothing the grid just disappears and once again no chat is displayed, I love the look of your mod but so far cant get it to run not sure if its something im doing wrong or a break in the latest version of forge
![untitled](https://f.cloud.github.com/assets/2360198/693454/a92e4b2e-dc89-11e2-94ac-8f63f95b5c77.png)

**Comment by Vazkii** [comment]
That is the NEI mob spawn grid, it has nothing to do with my mod. You can change the keybind either in the controls menu for mine, or in the NEI settings menu for NEI's:

**Comment by soulgriever** [comment]
Ah well you were right about the grid, however the mod is still doing nothing, pulled out NEI now no grid shows up, keybind is set, gencreator shows as loaded in forge mods but beyond that nothing, no more grid, no console output when pressing the key that is binded to gencreator

**Comment by Vazkii** [comment]
I don't know what's causing that...

**Comment by soulgriever** [comment]
tried the mod just now with just forge and no other mods installed, still no dice, can you try it with the latest version of forge 7.8.1 I just want to know if I am the only one having this issue sorry

**Comment by Vazkii** [comment]
Can you rebind the key to something else and press it while looking at a block on the ground (in creative)? I noticed you'er on survival in that picture. The mod only works in creative.

**Comment by soulgriever** [comment]
I must sincerely apologize, it was that I was not in creative must of missed that somewhere, everything is working now, sorry for your trouble
